### ISSUE TITLE
looping issue

### ISSUE THREAD

**Issue by abeazam** [nicklockwood/iCarousel#10]
setup:
added 6 items 
all visible on the screen at the same time 
enabled infinite scrolling

when u scroll all the way round from the first item back to the first item. Scrolling to the left(does not happen to the right). once u rech the first item again it does a full loop. 

thx

**Comment by chakery** [comment]
@nicklockwood 
hi, Nick
About infinite loops scrolling.
I did not find the `carouselShouldWrap ` delegate.
Here are all the delegate I have found.
![qq20170320-124815](https://cloud.githubusercontent.com/assets/9679029/24089012/5ff73886-0d6c-11e7-8703-b572effb00fb.png)

pls help.
Thx.

**Comment by iBCode** [comment]
@Chakery

**Comment by iBCode** [comment]
@Chakery 
Just return `YES` for option  `iCarouselOptionWrap` in the delegate method `- (CGFloat)carousel:(iCarousel *)carousel valueForOption:(iCarouselOption)option withDefault:(CGFloat)value;
`,  the rest return default values. 

`- (CGFloat)carousel:(iCarousel *)carousel valueForOption:(iCarouselOption)option withDefault:(CGFloat)value {
    switch (option) {
        case iCarouselOptionWrap:
            return YES;
            
        default:
            return value;
    }
}`

**Comment by iBCode** [comment]
@Chakery 
Just return `YES` for option  `iCarouselOptionWrap` in the delegate method `- (CGFloat)carousel:(iCarousel *)carousel valueForOption:(iCarouselOption)option withDefault:(CGFloat)value`, the rest return default values. That should work. 

```
- (CGFloat)carousel:(iCarousel *)carousel valueForOption:(iCarouselOption)option withDefault:(CGFloat)value {
    switch (option) {
        case iCarouselOptionWrap:
            return YES;
            
        default:
            return value;
    }
}
```
