### ISSUE TITLE
Linear Carousel with Zoomed In Center Item

### ISSUE THREAD

**Issue by nagendran-n** [nicklockwood/iCarousel#136]
**This is not an issue, but a request for help**

I am using your wonderful library for a project where we need to display 5 items in a carousel. The center item is zoomed to a 450x450 size image while the other 4 items should be displayed at a 0.39 scale of the original image.

If I set the itemWidth to 320 I can only see 3 items in the carousel. If I set it to 240 or something like that, I can see 5 items in the carousel, but the zoomed in view in the center overlaps the 2 views on the side.

Is there someway I can get the feature of a zoomed in view in the center (with a different itemwidth) and other visible items (with a different itemwidth)

Thanks for the awesome library.

**Comment by jenniferlim** [comment]
Just really cool to see that a comment [posted in 2012](https://github.com/nicklockwood/iCarousel/issues/136#issuecomment-5925361) is still relevant! 

Thanks @nicklockwood.

**Comment by HariNarayanan777** [comment]
Really super.. @nicklockwood

**Comment by akocaman** [comment]
Swift 4 version of @nicklockwood 's answer.

```
    func carousel(_ carousel: iCarousel, itemTransformForOffset offset: CGFloat, baseTransform transform: CATransform3D) -> CATransform3D {
        let distance : Float = -300
        let z = fminf(1.0, fabsf(Float(offset))) * distance
        return CATransform3DTranslate(transform, offset * carousel.itemWidth, 0.0, CGFloat(z))
    }
```

**Comment by gaurishankar7827** [comment]
demo link please
