### ISSUE TITLE
wrap not working

### ISSUE THREAD

**Issue by epichouseprojects** [nicklockwood/iCarousel#155]
Using iCarouselTypeCoverFlow2 

and set the property wrap = YES didnt work

also tried 
- (BOOL)carouselShouldWrap:(iCarousel *)carousel
  {
  //set up data
  return YES;
  }

also didnt work.

any ideas?

**Comment by RamdhaSOi** [comment]
- (CGFloat)carousel:(iCarousel *)carousel valueForOption:(iCarouselOption)option withDefault:(CGFloat)value{
    if(option == iCarouselOptionWrap){
     return YES;
    }
    return value;
}

Its works like charm. Try this

**Comment by chakery** [comment]
@RamdhaSOi 
hi, RamdhaSOi
About `-(CGFloat)carousel:(iCarousel *)carousel valueForOption:(iCarouselOption)option withDefault:(CGFloat)value` delegate
The return value is of type CGFloat, return YES, can you through compile ?
