### ISSUE TITLE
How to build multiple carousels which are not using fullscreen

### ISSUE THREAD

**Issue by pjaegerhh** [nicklockwood/iCarousel#157]
Hi,

I tried to tweak the demo's a bit to test if iCarousel might be feasible for my project. I'd like to have 2 or 3 vertical carousels side-by-side which are not using the entire screen but just the view ( e.g. 240x320) which they are part off. Tapping only works inside the view but unfortunately all the item's in the carousel which are not the current one fly out of the view overlapping the rest of the screen.

Any help / sample would be highly appreciated,

Thx, Peter

**Comment by scchess** [comment]
Thanks. This still work as of 2017.
