### ISSUE TITLE
carousel:viewForItemAtIndex: reusingView method question

### ISSUE THREAD

**Issue by liuyong** [nicklockwood/iCarousel#167]
HI，你好，我是来自中国的一名iphone应用软件开发者，我在使用  iCarousel 过程中，遇到一个问题，- (UIView *)carousel:(iCarousel *)carousel viewForItemAtIndex:(NSUInteger)index reusingView:(UIView *)view;  函数中得到的index 值是无序的，请问怎么才能得到跟 items 相对应的，顺序的索引？我目前折衷的做法是在函数- (void)carousel:(iCarousel *)carousel didSelectItemAtIndex:(NSInteger)index；中来通过点击实现我想要的功能。  期待你的回复，非常感谢!

HI, Hello, I'm an iphone application developers from China, I encountered a problem in use iCarousel process - (the UIView *) A carousel: (iCarousel *) A carousel viewForItemAtIndex: (NSUInteger) index reusingView: (UIView *) view; function index values ​​are unordered, I ask how to get with the items corresponding to the order of the index?I am currently a compromise approach is in the function - (void) A carousel: (iCarousel *) A carousel didSelectItemAtIndex: (NSInteger) index; by clicking I want.Look forward to your reply, Thank you very much!

**Comment by shaniraaj** [comment]
i have same problem with my code when the view is loaded i am printing the indexes and the indexes are not increasing in likewise 0 1 2 3 4 etc manner i have checked the condition for view

**Comment by nicklockwood** [comment]
@shaniraaj paste your `viewForItemAtIndex:` method and I'll take a look.

**Comment by nicklockwood** [comment]
@shaniraaj but if you are printing the index when view is loaded, it still won't be in order, because the views aren't loaded in order, as I said above.

**Comment by shaniraaj** [comment]
if (view==nil) {
            if ([carousel isEqual:self.firstCarousel])
            {
                SettingColor * setColor=[color objectAtIndex:index];
                NSLog(@"Index color %d with code=%@",(int)index,setColor.code);
                view=[[JAMSVGImageView alloc]initWithFrame:CGRectMake(self.view.frame.size.height-50,self.view.frame.size.height-50,100,100)];
                ((JAMSVGImageView*)view).backgroundColor=[UIColor colorFromString:setColor.code];
               
            }
            if ([carousel isEqual:self.secondCaurosel]) {
                SettingColor  * setColor=[color objectAtIndex:colorIndex];
                NSLog(@"Index color %d with code=%@",(int)index,setColor.code);
                view=[[JAMSVGImageView alloc]initWithFrame:CGRectMake(self.view.frame.size.height-50,self.view.frame.size.height-50,100,100)];
                ((JAMSVGImageView*)view).backgroundColor=[UIColor colorFromString:setColor.code];
                colorIndex++;
            }
In the above code there are two carousels and SettingColor is the class of color objects and 
"color" is an nsarray with size 24

when the above code is been executed the first caurosel loads 12 elements and the second caurosel also loads the same i am setting both views to same 
please help me out through it

**Comment by shaniraaj** [comment]
Thank for your help i found a solution which is working good.
Thanks for you help.

**Comment by Sankar-BseTec** [comment]
Hi Nick, is it possible to show number of  iCarousel's  inside custom cells in a tableview?
