### ISSUE TITLE
Loading Multiple Nib's into the one carousel

### ISSUE THREAD

**Issue by Mark117** [nicklockwood/iCarousel#169]
Hi there, 

I'm loving iCarousel, it's an unbelievable powerful too, but there's one thing I'm unable to get my head around and that's loading 2 or more different nibs into the one carousel. 

Is this possible at all to do? I'm imagining that I have to insert code in

```
- (UIView *)carousel:(iCarousel *)carousel viewForItemAtIndex:(NSUInteger)index reusingView:(UIView *)view
```

but i've no idea how to accomplish my task. Would you be able help please?

Also, is it possible to change the item that the app opens on, eg: currently the app (the controls demo), opens on item 1, is it possible to open it on say item 7? Is that just a reference to the index path?

**Comment by kamarshad** [comment]
Hello @nicklockwood 

I have to use Multiple Nib's into the one carousel 

Actually I want to display set of [T1,T2,T3] different kind of View and each T1,T2 ..... could have more than one different content, let say T1= 4, T2 = 5, and T3 = 3 (this content may increase).

As you said above we can create/load as much view on carousel by getting rid of the if(view == nil) check.
So if I create each time new instance for T1,T2,T3 how would carousel view manage memory for such condition ? don't you think doing so each time memory will increase simultaneously ?

Please help me.

**Comment by nicklockwood** [comment]
The reusingView optimisation is to improve performance by avoiding an alloc/dealloc for each view that appears on screen.

Removing it means the nibs must lpad as you scroll, which will be slightly slower, but should still be fine if the view is simple.

Your memory usage won't increase at all, because nib views will be released as soon as they move offscreen.

**Comment by kamarshad** [comment]
Thanks for your reply and making my doubts clear 
Thanks @nicklockwood
