### ISSUE TITLE
Large memory consumption for 50 items

### ISSUE THREAD

**Issue by lexar** [nicklockwood/iCarousel#171]
Greetings!

I use up to 50 views as items in an iCarousel in an iPhone app.
Each view consists of an empty UIView as container, an UIImageView with an Image and a Label with some text.
The images are between 100 and 300 KB each. Total size of all images is about 16MB.

When I start the app, I create all item views in advance for giving it to iCarousel quickly when it requests it. The memory consumption after creating all views pends at 30 MB with 4 items already loaded in the carousel.

When I scroll through all images, memory consumption increases constantly until, when the last view is reached, about 110 MB are consumed.
I tested this a lot with instruments and always reached the same results, iCarousel, when loading the views, needs 1-2 MB for each view attached. 

Can anyone confirm this behaviour, and even better, has an advice how to handle this?

Thanks a lot in advance!

**Comment by renatoDutraSilva** [comment]
Hi, I am having the exact same issue using swift 5. I know the this repository isn't updated in a while but I was wondering if someone could still help out.

Thanks!
