### ISSUE TITLE
Calling reloadData causes views to overlap when scrolled

### ISSUE THREAD

**Issue by jackhumphries** [nicklockwood/iCarousel#196]
When I call reloadData on the carousel, everything is refreshed. When I scroll though, the old views are still there and overlap with the new views. Here are two pictures (before and after):

www.chillysky.com/Before.png
www.chillysky.com/After.png

Any idea why this is happening?

**Comment by shanuu1809** [comment]
When i am loading the views label at index 1 disappears. Dont know what to do?

-(UIView *)carousel:(iCarousel *)carousel viewForItemAtIndex:(NSInteger)index reusingView:(UIView *)view
{
    UILabel *label = nil;
    UILabel *lblseater = nil;
    UILabel *lbltransmission = nil;
    UILabel *labelairbag = nil;
    UIImageView *img1 = nil;
    UIImageView *seats = nil;
    UIImageView *gears = nil;
    UIImageView *belts = nil;
    const NSInteger labelTag = 1;
    const NSInteger lblseaterTag = 2;
    const NSInteger lbltransmissionTag = 3;
    const NSInteger lblairbagTag = 4;
    const NSInteger lblimgTag = 5;

    //create new view if no view is available for recycling
    
//    if (view == nil)
//    {
        view = [[UIImageView alloc] initWithFrame:CGRectMake(0, 0, 200.0f, 200.0f)];
        ((UIImageView *)view).image = [UIImage imageNamed:@"car-list-bg.png"];
//      ((UIImageView *)view).image = [UIImage imageNamed:@"car-list-bg-white@3x.png"];
        
        view.contentMode = UIViewContentModeCenter;
        label = [[UILabel alloc] initWithFrame:CGRectMake(45, 110, 105, 12)];
        label.backgroundColor = [UIColor clearColor];
        label.textAlignment = NSTextAlignmentCenter;
        label.textColor = [UIColor colorWithRed:234.0/255.0 green:164.0/255.0 blue:0.0/255.0 alpha:1.0];
        [label setFont:[UIFont fontWithName:@"TwCenMT-Bold" size:10.0]];
        label.tag = labelTag;
        [view addSubview:label];
        
        lblseater = [[UILabel alloc] initWithFrame:CGRectMake(35, 167, 50, 12)];
        lblseater.backgroundColor = [UIColor clearColor];
        lblseater.textAlignment = NSTextAlignmentCenter;
        lblseater.textColor = [UIColor colorWithRed:234.0/255.0 green:164.0/255.0 blue:0.0/255.0 alpha:1.0];
        [lblseater setFont:[UIFont fontWithName:@"TwCenMT-Bold" size:9.0]];
        lblseater.tag = lblseaterTag;
        [view addSubview:lblseater];

        lbltransmission = [[UILabel alloc] initWithFrame:CGRectMake(75, 167, 50, 12)];
        lbltransmission.backgroundColor = [UIColor clearColor];
        lbltransmission.textAlignment = NSTextAlignmentCenter;
        lbltransmission.textColor = [UIColor colorWithRed:234.0/255.0 green:164.0/255.0 blue:0.0/255.0 alpha:1.0];
        [lbltransmission setFont:[UIFont fontWithName:@"TwCenMT-Bold" size:8.0]];
        lbltransmission.tag = lbltransmissionTag;
        [view addSubview:lbltransmission];

        labelairbag = [[UILabel alloc] initWithFrame:CGRectMake(115, 167, 50, 12)];
        labelairbag.backgroundColor = [UIColor clearColor];
        labelairbag.textAlignment = NSTextAlignmentCenter;
        labelairbag.textColor = [UIColor colorWithRed:234.0/255.0 green:164.0/255.0 blue:0.0/255.0 alpha:1.0];
        [labelairbag setFont:[UIFont fontWithName:@"TwCenMT-Bold" size:8.0]];
        labelairbag.tag = lblairbagTag;
        [view addSubview:labelairbag];
        
        [[view viewWithTag:index]removeFromSuperview];
        img1 = [[UIImageView alloc] initWithFrame:CGRectMake(47, 5, 110, 90)];
        img1.tag = lblimgTag;
        [view addSubview:img1];
        
//        img1.image = [UIImage imageNamed:@"car1.png"];
        
        seats = [[UIImageView alloc] initWithFrame:CGRectMake(56, 155, 10, 10)];
        seats.image = [UIImage imageNamed:@"seats.png"];
        
        gears = [[UIImageView alloc] initWithFrame:CGRectMake(96, 155, 10, 10)];
        gears.image = [UIImage imageNamed:@"gears.png"];
        
        belts = [[UIImageView alloc] initWithFrame:CGRectMake(135, 155, 10, 10)];
        belts.image = [UIImage imageNamed:@"belts.png"];
    
        [view addSubview:seats];
        [view addSubview:gears];
        [view addSubview:belts];
    
    lblseater.text = @"5 Seater";
    
    labelairbag.text = @"3 Airbags";
    
    NSString *carName = [iCarouselFilterItems objectAtIndex:index];

    NSString *str_trans = [dict_transmission_data valueForKey:carName];
    [lbltransmission setText:str_trans];
    
    NSString *str_img = [dict_vehicle_images valueForKey:carName];
    
    if ([carName isEqualToString:@""])
    {
        [label setText:@"Name"];
    }else
    {
        [label setText:carName];
    }
    
    
    if ([str_img isEqualToString:@""])
    {
        [img1 setImage:[UIImage imageNamed:@"car1"]];
    }else
    {
        NSString *vehicleimg = [NSString stringWithFormat:@"%@%@", imgurl, str_img];
        [self getServerImages:vehicleimg : img1];
    }
    
    return view;
    
}

**Comment by shanuu1809** [comment]
You can easily get to know my query through these screenshots.

![screen shot 2018-02-05 at 5 17 32 pm](https://user-images.githubusercontent.com/36156491/35803082-8b58f0ee-0a98-11e8-8678-8772dff44348.png)
![screen shot 2018-02-05 at 5 17 42 pm](https://user-images.githubusercontent.com/36156491/35803085-8b83493e-0a98-11e8-8ccd-bf7214f212c5.png)
![screen shot 2018-02-05 at 5 17 57 pm](https://user-images.githubusercontent.com/36156491/35803086-8ba97014-0a98-11e8-8144-10586742347f.png)
