### ISSUE TITLE
Scrolling one at a time

### ISSUE THREAD

**Issue by gusabdala** [nicklockwood/iCarousel#247]
I wanted to make the change so that when you swipe it scrolls a maximum of 1 item in that direction instead of multiple. . Seems like a simple change but I can't seem to figure it out. Any help would be a appreciated.

**Comment by vincentnock** [comment]
For those who end up on this issue like me, iCarousel now supports single-page swiping by setting pagingEnabled=YES.

**Comment by kamabhavik** [comment]
i still have issues with scrolling two or 2 or 3 page at a time.i want to restrict it by only one page at any time.i am using rotray type of carousle.can anyone please let me know if this is possible? with swipe right and left gesture it will be swipe only but user will not have manully scroll smoothly.

**Comment by pk75** [comment]
Works like a charm pagingEnabled=YES. thanks @nicklockwood  @vincentnock
