### ISSUE TITLE
Hello, I want to change the space between views in iCarouselTypeLinear

### ISSUE THREAD

**Issue by mustafaibrahim989** [nicklockwood/iCarousel#254]
Hello, I want to change the space between views in iCarouselTypeLinear, how i can do that

**Comment by JokerXu** [comment]
when the num of items is too little,for example num = 4,the iCarouselTypeLinear view result do not appear .my items width = screen bounds.width*0.5.

**Comment by RaghavaNaidu46** [comment]
Need to display items with dynamic widths. i have tried bellow code. but its increasing spaces between items too. here is my code: 

- (UIView *)carousel:(iCarousel *)carousel viewForItemAtIndex:(NSInteger)index reusingView:(UIView *)view
{

    UILabel *label = [[UILabel alloc]init];
    label.font = [UIFont systemFontOfSize:13];
    label.text = [timelineMediaArray objectAtIndex:index];
    label.textAlignment = NSTextAlignmentCenter;

    CGFloat width = [label.text sizeWithAttributes:@{NSFontAttributeName:[UIFont systemFontOfSize:13 ]}].width;
    label.frame = CGRectMake(0, 0, width+20,30);
    label.backgroundColor = [UIColor redColor];
    label.textColor = [UIColor whiteColor];


    return label;

} 

and the output is
![screen shot 2017-01-17 at 1 45 08 pm](https://cloud.githubusercontent.com/assets/12371030/22017744/9514052e-dcd1-11e6-8708-e25e4126232d.png)

**Comment by nicklockwood** [comment]
iCarousel doesn't support dynamic widths - all items must have the same width. You'll need to use UICollectionView.
