### ISSUE TITLE
How to retrieve correct index of current view

### ISSUE THREAD

**Issue by ghost** [nicklockwood/iCarousel#267]
Hi Nick, 

I'm using iCarousel to create a carousel of UIButtons. I looked at the button demo and managed to integrate it successfully. When a button is tapped, the NSInteger index = [carousel indexOfItemViewOrSubview:sender] method retrieves the correct index, no problem. 

The problem comes when I want a UILabel to update with info about the button, as one scrolls through the buttons. (In this instance I am displaying info about the In-App Purchase the button links to). 

I call: 

NSString *productDescription = [productDescriptions objectAtIndex:index];
        [infoLabel setText:productDescription];

inside the viewForItemAtIndex method, but of course, the index does not correctly represent the current  visible button, and I'm not sure how to retrieve it. When I output the index (even outside the if (button == nil) code, I get funny results. 

How would you suggest I update the UILabel in the viewForItemAtIndex method? 

Many thanks, and thanks for such excellent and useful code. 

Michael

**Comment by suneelseelam** [comment]
Hi, Iam using Icarousel invertedTimeMachine can u help me to show the current selected image name in label .
I have checked out objc code is available  but there is no code in swift available pls help in in doing swift code 
thanks in advance.
