### ISSUE TITLE
Custom time machine carousel with some tweaks

### ISSUE THREAD

**Issue by TeoCris** [nicklockwood/iCarousel#275]
Hi Nick,

I am trying to come up with my own carousel but I haven't been able to get it right...
Basically, I'm trying to achieve a carousel based on the inverted time machine with the following tweaks:
- the item views should be tilted, that means that even the current selected item is tilted not straight like in the default time machine carousel
- the item views should be stacked exactly as in the inverted time machine
- the motion should be that when I scroll the carousel the current item should slide to one side and go off screen.

Here is what I tried so far:

```
    CGFloat MAX_SCALE = 1.2f; //max scale of center item
    CGFloat MAX_SHIFT = 10.0f; //amount to shift items to keep spacing the same

    CGFloat shift = fminf(1.0f, fmaxf(-1.0f, offset));
    CGFloat scale = 1.0f + (1.0f - fabs(shift)) * (MAX_SCALE - 1.0f);
    transform = CATransform3DRotate(transform, -M_PI / 12.0f, 0.0f, 1.0f, 0.0f);
    transform = CATransform3DTranslate(transform, offset * carousel.itemWidth + shift * MAX_SHIFT, 0.0f, offset * carousel.itemWidth);
    return CATransform3DScale(transform, scale, scale, scale);
```

I was thinking that if I combine rotation, translation and finally scale I should be able to achieve the effect explained above. However, the slide to one side doesn't feel right ....

Thanks in advance.

**Comment by gheatley** [comment]
Here's the Swift 4 translation for those whom it may help.

```
let deltaX: CGFloat = 10
        let deltaZ: CGFloat = 20
        let originX: CGFloat = 0
        let originZ: CGFloat = 0
        
        var newTransform: CATransform3D = transform
        
        if offset >= 0 {
            
            newTransform = CATransform3DRotate(transform, (-.pi)/8.0, 0.0, 1.0, 0.0)
            newTransform = CATransform3DTranslate(newTransform, originX + offset * deltaX, 0, originZ - offset * deltaZ)
            
        } else if (offset < 0 && offset >= -1) {
            
            let newOffset: CGFloat = CGFloat(1 - fabsf(Float(offset)))
            newTransform = CATransform3DRotate(transform, newOffset * (-.pi) / 8.0, 0.0, 1.0, 0.0)
            newTransform = CATransform3DTranslate(newTransform, originX + offset * carousel.itemWidth * 1.1, 0, originZ + offset * deltaZ)
        
        } else if offset < -1 {
            
            newTransform = CATransform3DTranslate(transform, originX + offset * carousel.itemWidth * 1.1, 0, originZ - deltaZ)
            
        }
        
        return newTransform
```

**Comment by AdnanAfsari** [comment]
Hi gheatley 
i am trying to get a Custom Carousel like this .Can you help me with that??
<img width="287" alt="screen shot 2018-04-18 at 17 59 35" src="https://user-images.githubusercontent.com/8613710/38930731-b6c6dc32-4332-11e8-927c-11608dca809d.png">
