### ISSUE TITLE
Hi how can i change the size of a icarouselview item.

### ISSUE THREAD

**Issue by stefanaerts** [nicklockwood/iCarousel#355]
![pastedgraphic-2](https://f.cloud.github.com/assets/3684599/511612/0a11f282-be09-11e2-9258-92dedd782db6.png)

If i change the frame size it changes only the size of the images.
So i want the images closer to each other. 

if set the frame of the image like this:
-(UIView *)carousel:(iCarousel *)carousel viewForItemAtIndex:(NSUInteger)index reusingView:(UIView *)view
{
    if (view == nil) {
        view = [[JBAsyncImageView alloc] initWithFrame:CGRectMake(0, 0, 150, 150)];
    }

```
[(JBAsyncImageView *)view setImageURL:url];
[(JBAsyncImageView *)view setContentMode:UIViewContentModeScaleAspectFit];

 if i change the 150,150  it will change the image,but not the parent carouselItemWidth.
I just want more items closer to each other in the carousel.
```

Pls Can you help me.

Thanks

**Comment by gerchicov-bp** [comment]
why did you gave a possibility to change item width only? Why not to change it to return CGSize? I mean the situation when an app has multiple interface orientations and multiple item sizes for this reason.

**Comment by nicklockwood** [comment]
It's just for historical reasons - I didn't want to break backwards compatibility. But itemWidth is used for the height if the carousel is in vertical orientation.

**Comment by umab6666** [comment]
Hi, How can I increase the height of views which are in background(the side views). They look very small compared to the main view(the middle one).
