### ISSUE TITLE
Can't add shadow to carousel reflection view

### ISSUE THREAD

**Issue by vividcode** [nicklockwood/iCarousel#376]
I want to put drop shadow to my ReflectionView which is carousel view. I am putting following code:

```
- (UIView *)carousel:(iCarousel *)carousel viewForItemAtIndex:(NSUInteger)index reusingView:(ReflectionView     *)view
{
  //view creation and adding subviews
  view.layer.shadowColor = [UIColor redColor].CGColor;
  view.layer.shadowOffset = CGSizeMake(-2, 2);
  view.layer.shadowRadius = 2.0;
  view.layer.shadowPath = [UIBezierPath bezierPathWithRect:view.bounds].CGPath;  
  view.layer.masksToBounds = NO;   
  return view;
}
```

I am already overriding 'carouselItemWidth' with more width than 'viewForItemAtIndex' so that the view has space to display the shadow.

All reflections appear fine the only issue is with shadow.

I also tried to put this same code inside ReflectionView.m update method which creates the reflection part but with no result.

What am I missing?

**Comment by Abhishek-NickelFox** [comment]
@vividcode : Can you tell how i can remove shadow(bottom reflection of view)?

**Comment by nicklockwood** [comment]
@AbhishekNFX unless you are using ReflectionView in addition to iCarousel, there is no reflection. The reflection you see in the examples is baked into the background image.

**Comment by dengV** [comment]
@AbhishekNFX , the example image "page.png" is special
