### ISSUE TITLE
CoverFlow image repeat.

### ISSUE THREAD

**Issue by ilvito** [nicklockwood/iCarousel#401]
Hello i use this carousel:
carousel.type = iCarouselTypeCoverFlow2;

But when i scroll i see that carosuel repeat always the first 7 images. 
What i'm doing wrong??

This is my code:
- (NSUInteger)numberOfItemsInCarousel:(iCarousel *)carousel
  {
  //return the total number of items in the carousel
  return [items count];
  
  NSLog(@"%i",[items count]);
  }
- (UIView *)carousel:(iCarousel *)carousel viewForItemAtIndex:(NSUInteger)index reusingView:(UIView *)view
  {
  
  //create new view if no view is available for recycling
  if (view == nil)
  {
      view = [[[ReflectionView alloc] initWithFrame:CGRectMake(0.0f, 0.0f, 510.0f, 510.0f)] autorelease];
  
  ```
  //set up content
  
  ArtWorks *nuovoArtworks = [_ArtWorksTableResults objectAtIndex:index];
  
  
  
  // titolo del coverFlow //
  
  
  
  // titolo //
  
  
  
  
  
  UIImageView *image =[[UIImageView alloc] initWithFrame:view.bounds];
  image.layer.borderColor = [UIColor lightGrayColor].CGColor;
  image.layer.borderWidth = 2.0f;
  NSString *nomeFile = [NSString stringWithFormat:@"%@_flow",nuovoArtworks.audioFile];
  NSString *directory = [NSString stringWithFormat:@"webapp/content/%@",nuovoArtworks.id];
  NSString *filePath = [[NSBundle mainBundle]pathForResource:nomeFile ofType:@"jpg" inDirectory:directory];
  image.image = [UIImage imageWithContentsOfFile:filePath];
  view.contentMode = UIViewContentModeScaleAspectFill;
  
  
  
  [view addSubview:image];
  ```
  
  }
  else
  {
      //get a reference to the label in the recycled view
  }
  
  //set item label
  //remember to always set any properties of your carousel item
  //views outside of the `if (view == nil) {...}` check otherwise
  //you'll get weird issues with carousel item content appearing
  //in the wrong place in the carousel
  //label.text = [items[index] stringValue];
  
  return view;

}
- (CGFloat)carousel:(iCarousel *)carousel valueForOption:(iCarouselOption)option withDefault:(CGFloat)value
  {
  if (option == iCarouselOptionSpacing)
  {
      return value \* 2.3f;
  }
  return value;
  }

can you help me pls???
TY

**Comment by emiliomarin** [comment]
How did you fix it? it's happening to me too

**Comment by nicklockwood** [comment]
You should read the comment in the sample project code about not referring to index inside the `if (view != nil) {` block.

Views are recycled with at different positions, so if you only set the image the first time the view is created, it will show up at the wrong place in the carousel next time it used.

**Comment by emiliomarin** [comment]
Oh yes, it makes sense! thanks for the quick reply
