### ISSUE TITLE
Can't apply to UITableView Cell

### ISSUE THREAD

**Issue by Supertecnoboff** [nicklockwood/iCarousel#409]
I really like iCarousel and I must admit @nicklockwood you sir have done a great job!

However, I have one problem, I can't get iCarousel to apply to the UITableView cells INSTEAD of the UITableView itself. Is it possible to apply iCarousel to UiTableView cells instead??

Here is my code:

```
-(void)createIcarousel {
    categorySubView = [[iCarousel alloc]initWithFrame:CGRectMake(160, 274, 480, 125)];

    // CategorySubView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
    categorySubView.delegate = self;
    categorySubView.dataSource = self;
    categorySubView.type = iCarouselTypeCoverFlow2;
    [self.view addSubview:categorySubView];
}

-(NSUInteger)numberOfItemsInCarousel:(iCarousel *)carousel {
    //return [episodes count];
    return 10;
}

-(UIView *) carousel:(iCarousel *)carousel viewForItemAtIndex:(NSUInteger)index reusingView:(UIView *)view {
    //UITableView *sampleTable = [[UITableView alloc] initWithFrame:CGRectMake(0, 0, 150, 150) style:UITableViewStylePlain];
    //sampleTable.dataSource = self;
    //sampleTable.delegate = self;
    //[sampleTable setBackgroundColor:[UIColor blackColor]];

    return jsonTable;
}

-(BOOL)carousel:(iCarousel *)carousel shouldSelectItemAtIndex:(NSInteger)index{
    return YES;
}

-(CGFloat)carouselItemWidth:(iCarousel *)carousel {
    // Usually this should be slightly wider than the item views
    return 180;
}

-(UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    // Delegate call back for cell at index path.

    static NSString *CellIdentifier = @"Cell";
    CustomCell *cell = (CustomCell *)[tableView dequeueReusableCellWithIdentifier:CellIdentifier];

    if (cell == nil) {
        NSArray *nib = [[NSBundle mainBundle] loadNibNamed:@"CustomCell" owner:self options:nil];
        cell = [nib objectAtIndex: 0];
    }

    cell.username.text = [[[episodes objectAtIndex:indexPath.row] valueForKey:@"user"] valueForKey:@"username"];

    cell.username.clipsToBounds = YES;
    cell.profilepic.clipsToBounds = YES;
    cell.geo.clipsToBounds = YES;
    cell.picture.clipsToBounds = YES;
    cell.contentView.clipsToBounds = NO;
    cell.clipsToBounds = YES;

    return cell;
}
```

**Comment by wekancodemohammed** [comment]
@nicklockwood First of All Thanks for the iCarousel. I am also doing the something same as @Supertecnoboff  did. But it crashes by saying "Unrecognized selector sent in numberOfItemsInCarousel". Please help me on this. Thanks in advance..!

**Comment by nicklockwood** [comment]
@wekancodemohammed  It sounds like the object you've connected to carousel.dataSource doesn't implement the <iCarouselDataSource> protocol. Maybe it isn't your view controller? Or maybe it is, but you forgot to implement the protocol, or the numberOfItemsInCarousel method?

**Comment by wekancodemohammed** [comment]
Thanks for the Reply. Can't i add the iCarouselDelegate and iCarouselDataSource to the UITableViewCell? and implement in the same?

**Comment by nicklockwood** [comment]
@wekancodemohammed no.

**Comment by wekancodemohammed** [comment]
Ok Thanks,

**Comment by mahdiGithub1370** [comment]
hi 
can we put carouse in tableview cell?
I did it , but viewForItemAt don't call!
I can't understand why

**Comment by skvalibabu** [comment]
Hi @nicklockwood I really appreciate your effort and thank you for that .
Here I have a doubt, how to display carousal view effect inside a specific tableview cell (horizontally). 
For example I have  added a tabview to the view controller and given number cell count is 4
Now I have to show cell # 2 and cell # 4 consists of carousal effect views. 
How to achieve this functionality , there are delegate methods (Tableview datasource and iCarousalDataSoure) how to wake up the carousal effect at specified cell.

Thank you in advance...!
