### ISSUE TITLE
Autoscroll continues moving internally

### ISSUE THREAD

**Issue by joshuaseltzer** [nicklockwood/iCarousel#466]
I've downloaded the latest beta of iCarousel (1.8 Beta 9 I believe as of today, 1/20/14) to take advantage of the autoscroll feature that has been added.

Based on the documentation, the only property that controls the ability for the carousel to autoscroll is (naturally) the "autoscroll" property.

My goal is to allow the user to turn on and off this feature.  I'm using a tap+hold gesture recognizer to allow the user to turn on or off autoscrolling.  This functionality seems to work well - by doing a tap+hold when autoscrolling is off, I can set the property to a value between 0 and 1 (or -1 and 0) and it starts moving.  Another tap+hold, I set the value back to 0.0 and the carousel will stop visually.

However, it seems that there is something internally that isn't stopping the autoscrolling.  I'm drawing this conclusion because the next time the user performs a tap+hold to start the autoscroll again, the carousel jumps to a random spot further along the carousel.  This spot seems to depend on how long I wait between the last time I turned off autoscroll.

Nick, can you confirm for me that this is indeed a bug, or rather maybe I'm using the property incorrectly?  If you need more information or explanation, I'm happy to provide it.

Thanks for all of your work on this great class.

**Comment by ngoclt** [comment]
@CoBrA2168 : Thanks for your solution. It solves my problem.
 
>EDIT 2: I was able to fix the problem by resetting the "_lastTime" member variable when the autoScroll property is set. Here's the updated implementation for the setAutoScroll method:

```
- (void)setAutoscroll:(CGFloat)autoscroll
{
    if (_autoscroll != autoscroll)
    {
        _autoscroll = autoscroll;
        if (autoscroll != 0.0f) {
            _lastTime = CACurrentMediaTime();
            [self startAnimation];
        }
    }
}
```

>This resets the _lastTime variable to the current time right before the animation will occur. I haven't tested it enough to see if this causes any significant side affects, but it does solve the jumping scrolling problem when starting/stopping autoscroll.

**Comment by lubos08** [comment]
@CoBrA2168 Thanks, it works for me too!

**Comment by Autumnslash** [comment]
> EDIT 2: I was able to fix the problem by resetting the "_lastTime" member variable when the autoScroll property is set. Here's the updated implementation for the setAutoScroll method:
> 
> ```
> - (void)setAutoscroll:(CGFloat)autoscroll
> {
>     if (_autoscroll != autoscroll)
>     {
>         _autoscroll = autoscroll;
>         if (autoscroll != 0.0f) {
>             _lastTime = CACurrentMediaTime();
>             [self startAnimation];
>         }
>     }
> }
> ```
> 
> This resets the _lastTime variable to the current time right before the animation will occur. I haven't tested it enough to see if this causes any significant side affects, but it does solve the jumping scrolling problem when starting/stopping autoscroll.

I'm having the same issue, would you happen to know the Swift implementation of this fix? I'm not familiar with translating objc to Swift... tried... but no dice lol.
