### ISSUE TITLE
Reverse Direction of iCarousel

### ISSUE THREAD

**Issue by hirwish** [nicklockwood/iCarousel#478]
I want to scroll right to left in iCarousel. How is it possible without transforming it ?

**Comment by manojmashru** [comment]
@nicklockwood ,

Hope you are doing well.

In our app i have to support for RTL language(Arabic), and for Arabic language we have to flip all our layouts from Right To Left(Reverse).

In our app i am using linear type carousel, and for supporting Arabic language, iCarousel should animate in reverse direction without changing the data model(i.e. First item remains first and last remains last).
Just scroll direction will be reverse rest all remains same.

Kindly give me a solution to this issue.

**Comment by Neena-Mishra** [comment]
Hi @nicklockwood 

Hope you are doing great.

In our app we are syncing two carousels and somehow I achieved it using this method carouselDidEndDecelerating but, can you please reply how to get carousel scroll direction (horizontal) either it is scrolling in left direction or right direction and also it will be good if you can suggest other way to achieve this.

Thanks in advance and iCarousel is awesome.
