### ISSUE TITLE
Crashed in iPad 64bit 7.1 -->didMoveToSuperview-->startAnimation

### ISSUE THREAD

**Issue by interchen** [nicklockwood/iCarousel#498]
- (void)startAnimation
  {
  if (!_timer)
  {
      if (_useDisplayLink)
      {
# ifdef ICAROUSEL_IOS
# ifndef USING_CHAMELEON

```
        //support for Chameleon
        _timer = [CADisplayLink displayLinkWithTarget:self selector:@selector(step)];
        [_timer addToRunLoop:[NSRunLoop mainRunLoop] forMode:NSDefaultRunLoopMode];
```
# endif
# else

```
        CVDisplayLinkCreateWithActiveCGDisplays((void *)&_timer); 
        CVDisplayLinkSetOutputCallback((__bridge CVDisplayLinkRef)_timer, (CVDisplayLinkOutputCallback)&displayLinkCallback, (__bridge void *)self);
        CVDisplayLinkStart((__bridge CVDisplayLinkRef)_timer);
```
# endif

```
    }

    //use timer if display link
    //disabled or unavailable
    if (!_timer)
    {
        _timer = [NSTimer timerWithTimeInterval:1.0/60.0
                                         target:self
                                       selector:@selector(step)
                                       userInfo:nil
                                        repeats:YES];

        [[NSRunLoop mainRunLoop] addTimer:_timer forMode:NSDefaultRunLoopMode];
    }
}
```

}

**Comment by SaraMichel** [comment]
Hi nicklockwood,
I m using latest version of iCarousel for ipad and iphone both.
i need to use 44 images in coverflow but i received memory warnings 3 times while i will scroll coverflow and after that my app will crash.i found this issue in iPad side.

Here is the code i used  
This is my array : ---
theAssets=[NsMutableArray new];
totalNumberofCards=44
 if (UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPad) //For Ipad
 {
	for (NSInteger i = 1; i < (totalNumberofCards + 1); i++)
	{
	UIImage *realImg= [UIImage imageNamed:[NSString stringWithFormat:@"card_iPad_%@.jpg",i]];
	[theAssets addObject:image];			
	}
}

and this is the iCarousel delegate methods
#pragma mark iCarousel methods delegates

- (NSInteger)numberOfItemsInCarousel:(__unused iCarousel *)carousel1
{
	 return [theAssets count];
}

- (UIView *)carousel:(__unused iCarousel *)carousel1 viewForItemAtIndex:(NSInteger)index reusingView:(UIView *)view
{
           if (UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPad)
	   {
		view = [[UIImageView alloc] initWithFrame:CGRectMake(0, 0, 370.0f, 470.0f)];
	  }
	  else
	  {
               view = [[UIImageView alloc] initWithFrame:CGRectMake(0, 0, 160.0f, 225.0f)];
	  }
                   view.contentMode = UIViewContentModeCenter;
		  UIImageView *img=[[UIImageView alloc] initWithFrame:view.bounds];
                   img.clipsToBounds=YES;
		  img.image=[theAssets objectAtIndex:index];
		  [view addSubview:img];
		  return view;
	 }
}

please help me to solve this memory leaks.
