### ISSUE TITLE
Pull to refresh

### ISSUE THREAD

**Issue by Shukuyen** [nicklockwood/iCarousel#51]
Thanks for this awesome control! Do you think it is possible to implement something like "pull to refresh" with this? If so, how would you do it? 

Thanks,
Shukuyen.

**Comment by asifbilal786** [comment]
@Shukuyen , did you able to implement "pull to refresh" functionality using iCarousel view?

Also @nicklockwood it would be great if you post an example with "pull to refresh" functionality as well.
