### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by rahulvyas** [nicklockwood/iCarousel#554]
Hi Nick,

I am sorry to post this in issues section but I didn't find a way to message you.
I am unable to figure out how I can make Carousel like a half moon shape/smile shape ?
Could anyone help me out in this ?

**Comment by nicklockwood** [comment]
Use iCarouselTypeWheel and use the carousel:optionForKey delegate method to set the radius the number of visible items

**Comment by rahulvyas** [comment]
Thanks Man
