### ISSUE TITLE
index problem!

### ISSUE THREAD

**Issue by HsienYu** [nicklockwood/iCarousel#562]
Hi, 

When I use - (UIView *)carousel:(iCarousel *)carousel viewForItemAtIndex:(NSInteger)index reusingView:(UIView *)view{
} and try to check the index number by Nslog().

the index number isn't correct. For example , when I scroll to item 0. The index number will be 996.

**Comment by nicklockwood** [comment]
You shouldn't check the current index number from within that method.

Check it from within carouselDidScroll: instead, and use the carousel.currentItemIndex property.

**Comment by HsienYu** [comment]
thanks for your quick reply!!
sure, I did before. But I need to use  (UIView *)carousel:(iCarousel *)carousel viewForItemAtIndex:(NSInteger)index reusingView:(UIView *)view{} to add data from json, I need the proper index number to do that. Or do you have any other recommandation for that?

**Comment by HsienYu** [comment]
Hi, 
I think I got it. thank you very much!! I really appreciate your project!!

**Comment by nicklockwood** [comment]
The index number in carousel:viewForItemAtIndex: is correct for the view that is being created/recycled in that method, but that view isn't necessarily the one you just scrolled to because views have to be created before they appear on screen to avoid gaps.
