### ISSUE TITLE
Wrong current item index when reusing view and more than 10 items in carousel

### ISSUE THREAD

**Issue by gopaldevra** [nicklockwood/iCarousel#564]
I am using carousel type rotary , and i have array of custom objects around 14 and i need to refresh another view according to centered carousel item , for this i'm using currentItemIndex property of carousel. Sometimes it is not working as expected. It gives me wrong currentItemIndex.

**Comment by nicklockwood** [comment]
That shouldn't happen. Where are you calling currentItemIndex from?

**Comment by gopaldevra** [comment]
I've tried on these methods

-(void)carouselCurrentItemIndexDidChange:(iCarousel *)carousel
-(void)carouselDidEndScrollingAnimation:(iCarousel *)carousel
-(void)carouselDidEndDecelerating:(iCarousel *)carousel

**Comment by gopaldevra** [comment]
if we use reusing view then it not is not working as expected.

**Comment by nicklockwood** [comment]
carouselCurrentItemIndexDidChange: is the correct place. If you are finding that the reported index seems wrong, it is more likely that the index is correct, but the view that you are returning from viewForItemAtIndex:reusingView: is incorrect.

Many people get the implementation of viewForItemAtIndex:reusingView: wrong because they misunderstand the reuse mechanism and assume that if the reusingView parameter is non-nil, they don't need to do anything.

If you paste your viewForItemAtIndex:reusingView: implementation into the ticket, I'll check it for you.

**Comment by gopaldevra** [comment]
This method is as


- (UIView *)carousel:(iCarousel *)carousel viewForItemAtIndex:(NSInteger)index reusingView:(UIImageView *)view
{
    UILabel *label = nil;
    ChannelInfoModal *channel = self.arrayOfCarouselElements[index] ;
    
    
    //create new view if no view is available for recycling
    
//    if (view == nil)
//    {
//        
    
        if ( [[UIDevice currentDevice] userInterfaceIdiom] == UIUserInterfaceIdiomPhone) {
            
            view = [[UIImageView alloc] initWithFrame:CGRectMake(0, 0, 80.0f, 80.0f)];
            view.backgroundColor = [UIColor colorWithRed:242.0/255.0 green:242.0/255.0 blue:242.0/255.0 alpha:1];
            
            UIImageView *imgView = [[UIImageView alloc]init];
            imgView.frame = CGRectMake((view.frame.size.width/2)-35, (view.frame.size.height/2)-35, 70, 50);
            
            [view addSubview:imgView];
            
            UILabel *lblChannelNumber = [[UILabel alloc]init];
            lblChannelNumber.frame = CGRectMake(
                                                
                                                (view.frame.size.width/2)-35,
                                                
                                                imgView.frame.origin.y+imgView.frame.size.height,
                                                
                                                70,
                                                
                                                20);
            
            
            [lblChannelNumber setText:channel.channelNumber];
            
            [lblChannelNumber setTextColor:kColor_BlueTheme_TextToNearBlack] ;
            [lblChannelNumber setFont:[UIFont fontWithName:kFontHelveticaNeueRegular size:12]];
            lblChannelNumber.backgroundColor = kColor_BlueTheme_TextToNearWhite;
            [lblChannelNumber setTextAlignment:NSTextAlignmentCenter];
            [view addSubview:lblChannelNumber];
            
            
            
            
            
            NSString *ChannelName = [NSString stringWithFormat:@"%@",channel.channelName];
            
            UIImage *imageChannel = [UIImage imageNamed:ChannelName];
            [imgView setImage:imageChannel];
            
            view.contentMode = UIViewContentModeScaleAspectFit;
            
            
            
            label = [[UILabel alloc]initWithFrame:view.bounds];
            label.numberOfLines = 0;
            //label.lineBreakMode = NSLineBreakByCharWrapping;
            label.backgroundColor = [UIColor clearColor];
            
            if (SYSTEM_VERSION_LESS_THAN(@"6.0")) {
                label.textAlignment = UITextAlignmentCenter;
            }
            
            if (SYSTEM_VERSION_GREATER_THAN_OR_EQUAL_TO(@"7.0")) {
                label.textAlignment = NSTextAlignmentCenter;
            }
            
            else
            {
                label.textAlignment = NSTextAlignmentCenter;
            }
            
            // label.font = [label.font fontWithSize:10];
            [label setFont:[UIFont fontWithName:kFontHelveticaNeueBold size:1]];
            label.tag = 1;
            view.layer.borderColor = [UIColor lightGrayColor].CGColor;
            [view.layer setCornerRadius:5.0f];
            view.layer.borderWidth = 1.0f;
            label.layer.borderColor = [UIColor lightGrayColor].CGColor;
            [label.layer setCornerRadius:5.0f];
            label.layer.borderWidth = 1.0f;
            [view setClipsToBounds:YES];
            
            
            [view addSubview:label];
            
        }
        
        
        else
        {
            
            view = [[UIImageView alloc] initWithFrame:CGRectMake(0, 0, 170.0f, 170.0f)];
            view.backgroundColor = [UIColor colorWithRed:242.0/255.0 green:242.0/255.0 blue:242.0/255.0 alpha:1];
            
            UIImageView *imgView = [[UIImageView alloc]init];
            imgView.frame = CGRectMake((view.frame.size.width/2)-80, (view.frame.size.height/2)-55, 160, 110);
            
            [view addSubview:imgView];
            
            
            UILabel *lblChannelNumber = [[UILabel alloc]init];
            lblChannelNumber.frame = CGRectMake(
                                                
                                                (view.frame.size.width/2)-80,
                                                
                                                imgView.frame.origin.y+imgView.frame.size.height,
                                                
                                                160,
                                                
                                                40);
            
            
            [lblChannelNumber setText:channel.channelNumber];
            
            [lblChannelNumber setTextColor:kColor_BlueTheme_TextToNearBlack] ;
            [lblChannelNumber setFont:[UIFont fontWithName:kFontHelveticaNeueRegular size:12]];
            lblChannelNumber.backgroundColor = kColor_BlueTheme_TextToNearWhite;
            [lblChannelNumber setTextAlignment:NSTextAlignmentCenter];
            [view addSubview:lblChannelNumber];
            
            
            
            NSString *ChannelName = [NSString stringWithFormat:@"%@",channel.channelName];
            
            UIImage *imageChannel = [UIImage imageNamed:ChannelName];
            [imgView setImage:imageChannel];
            
            view.contentMode = UIViewContentModeScaleAspectFit;
            
            
            label = [[UILabel alloc]initWithFrame:view.bounds];
            label.numberOfLines = 0;
            label.backgroundColor = [UIColor clearColor];
            
            if (SYSTEM_VERSION_LESS_THAN(@"6.0")) {
                label.textAlignment = UITextAlignmentCenter;
            }
            
            if (SYSTEM_VERSION_GREATER_THAN_OR_EQUAL_TO(@"7.0")) {
                label.textAlignment = NSTextAlignmentCenter;
            }
            
            else
            {
                label.textAlignment = NSTextAlignmentCenter;
            }
            
            label.font = [label.font fontWithSize:32.0f];
            label.tag = 1;
            view.layer.borderColor = [UIColor lightGrayColor].CGColor;
            [view.layer setCornerRadius:5.0f];
            view.layer.borderWidth = 1.0f;
            label.layer.borderColor = [UIColor lightGrayColor].CGColor;
            [label.layer setCornerRadius:5.0f];
            label.layer.borderWidth = 1.0f;
            [view setClipsToBounds:YES];
            
            
            [view addSubview:label];
            
            
        }
   // }
//    else
//    {
//        //get a reference to the label in the recycled view
//        label = (UILabel *)[view viewWithTag:1];
//    }
    
    
    label.font = [UIFont fontWithName:kFontHelveticaNeueRegular size:16];
    //ChannelInfoModal *channel = self.arrayOfCarouselElements[index] ;
    // label.text = channel.channelName;
    
    return view;
}

**Comment by gopaldevra** [comment]
have you got a chance to look at this issue ?

**Comment by phantomlight** [comment]
was anyone able to fix this issue?

**Comment by gopaldevra** [comment]
I commented the code of reusing of view as and It's working nice.

// if (view == nil)
// {
// }

**Comment by dogo** [comment]
yep, the bug only occurs if you try to reuse

**Comment by dogo** [comment]
hmm was my fault

Wrong Code

```Objective-C
- (UIView*)carousel:(iCarousel *)carousel viewForItemAtIndex:(NSInteger)index reusingView:(UIView *)view {
    Avatar *avatar = _avatarList[index];
    
    //create new view if no view is available for recycling
    if (view == nil) {
        view = [[UIImageView alloc] initWithImage:[UIImage imageNamed:@"placeholder"]];
        view.backgroundColor = [UIColor clearColor];
        view.tag = 1;
        
        [((UIImageView *)view) sd_setImageWithURL:avatar.largeImageURL placeholderImage:[UIImage imageNamed:@"placeholder"]];
        ((UIImageView *)view).contentMode = UIViewContentModeScaleAspectFit;
    } else {
        E4L_LOG(@"Using recycled view");
        //get a reference to the recycled view
        view = (UIImageView *)[view viewWithTag:1];
    }    
    return view;
}
```

Right code

```Objective-C
- (UIView*)carousel:(iCarousel *)carousel viewForItemAtIndex:(NSInteger)index reusingView:(UIView *)view {
    Avatar *avatar = _avatarList[index];
    
    //create new view if no view is available for recycling
    if (view == nil) {
        view = [[UIImageView alloc] initWithImage:[UIImage imageNamed:@"placeholder"]];
        view.backgroundColor = [UIColor clearColor];
        view.tag = 1;
        
        ((UIImageView *)view).contentMode = UIViewContentModeScaleAspectFit;
    } else {
        E4L_LOG(@"Using recycled view");
        //get a reference to the recycled view
        view = (UIImageView *)[view viewWithTag:1];
    }
    
    //remember to always set any properties of your carousel item
    //views outside of the `if (view == nil) {...}` check otherwise
    //you'll get weird issues with carousel item content appearing
    //in the wrong place in the carousel
    [((UIImageView *)view) sd_setImageWithURL:avatar.largeImageURL placeholderImage:[UIImage imageNamed:@"placeholder"]];
    
    return view;
}
```

We have to set the image outside `if - else` block

**Comment by Cipherdale** [comment]
@dogo where do you put sd_cancelCurrentImageDownload, if u use SDWebImage with iCarousel?

**Comment by nicklockwood** [comment]
@episquare you should put it inside the `else`, after `view = (UIImageView *)[view viewWithTag:1];`

**Comment by Cipherdale** [comment]
@nicklockwood owwww, my bad.... thanks for tha fast respond, really love this library, it's working very great in Swift 4 :)
