### ISSUE TITLE
Problems with using iCarousel with UINavigationController

### ISSUE THREAD

**Issue by iqw** [nicklockwood/iCarousel#570]
Hi, i have some issue, when i put carousel in controller pushed by UINavigationController.

When i do it - carousel don't have any items, unless i move self.items init in constructor method.
It works well, but when i press back button  of navigation bar - previous carousel item stay on screen (with previous view controller) for at least 1 sec. 

Tried to unset carousel on back button clicked, but it wasnt give any effect.

Repeated this to example project (added UINavigationController before carousel controller) and see this issue again. Is it way for fix this issue?

If any examples needed - can add some code here, but unfortunately without screenshots, because effect disappeared so fast, and i just cant take screenshot. Thanks.

**Comment by nicklockwood** [comment]
you probably need to set clipsToBounds = YES on the carousel.

**Comment by nicklockwood** [comment]
If that doesn't fix it, it's possible you are adding multiple copies of the carousel view to your view hierarchy, or not removing them correctly.

**Comment by iqw** [comment]
Thanks a lot for clipsToBounds, it fixed the problem, sorry, learn your library by examples and and didnt saw this param. Thanks!
