### ISSUE TITLE
Incompatible with wpmandrill

### ISSUE THREAD

**Issue by silverhawk184** [nicklockwood/iCarousel#580]
Hello,

I have an issue on my site with running mandrill and iCarousel. When both plugins are running, Wordpress gives me the message "Mandrill: wp_mail has been declared by another process or plugin, so you won't be able to use Mandrill until the problem is solved." As soon as I disable iCarousel, the issue goes away. I have disabled all other plugins.

**Comment by nicklockwood** [comment]
I believe you are talking about a different iCarousel. This is the github page for the native Objective-C iPhone control.
