### ISSUE TITLE
Make Next and Previous image blur

### ISSUE THREAD

**Issue by maulikpat** [nicklockwood/iCarousel#582]
Hi Nik,

I am using this library in my app. I am using iCarouselTypeLinear type. What I want is, make previous and upcoming next image blur. I know how to make blur. But I want to know how I can get previous and next view while scrolling. 

Also, when should I process the image after scroll did end or while scrolling ?

Any suggestions ?

Thanks.

**Comment by nicklockwood** [comment]
The best place to put your logic is probably in the carouselDidScroll: delegate method.

You can access all of the visible carousel views by index, so to get the previous and next views, use:

    UIView *previous = [carousel itemViewAtIndex:carousel.currentItemIndex - 1];
    UIView *next = [carousel itemViewAtIndex:carousel.currentItemIndex + 1];

You may also want to vary the amount of blur based on the offset, in which case you can use -[carousel offsetForItemAtIndex:] to get a floating point value.

**Comment by maulikpat** [comment]
Nik,

When index is 0 then 
UIView *previous = [carousel itemViewAtIndex:carousel.currentItemIndex - 1];
it returns nil.

How should I handle this ?

**Comment by nicklockwood** [comment]
If it's a wrapped carousel, use:

    NSInteger nextIndex = carousel.currentItemIndex % carousel.numberOfItems;
    NSInteger prevIndex = (carousel.currentItemIndex + carousel.numberOfItems - 1) % carousel.numberOfItems;

**Comment by maulikpat** [comment]
I think
NSInteger nextIndex = carousel.currentItemIndex % carousel.numberOfItems;
returns current index not the next index. As the log as 3 3 2

**Comment by nicklockwood** [comment]
Sorry, typo, that should have been

    NSInteger nextIndex = (carousel.currentItemIndex + 1) % carousel.numberOfItems

**Comment by maulikpat** [comment]
Yes. It worked. Thanks.

I wrote my logic as you suggested in DidScroll: like

- (void)carouselDidScroll:(iCarousel *)carousel
{
    NSInteger nextIndex = (carousel.currentItemIndex + 1) % carousel.numberOfItems;
    UIView *next = [carousel itemViewAtIndex:nextIndex];
    AsyncImageView *nextImageView = (AsyncImageView *)[next viewWithTag:101];
    if (nextImageView.image)
    {
        UIImage *blurImage = [UIImageEffects imageByApplyingLightEffectToImage:nextImageView.image];
        nextImageView.image = blurImage;
    }
    
    UIView *current = [carousel itemViewAtIndex:carousel.currentItemIndex];
    AsyncImageView *currentImageView = (AsyncImageView *)[current viewWithTag:101];
    if (currentImageView.image)
    {
        HomeThemeData *data = (HomeThemeData *)[self.rotatingImagesArray objectAtIndex:carousel.currentItemIndex];
        currentImageView.imageURL = [NSURL URLWithString:data.ITEM_PATH];
        currentImageView.backgroundColor = [UIColor clearColor];
        current.backgroundColor = [UIColor clearColor];
        current.clipsToBounds = YES;
    }
    
    NSInteger prevIndex = (carousel.currentItemIndex + carousel.numberOfItems - 1) % carousel.numberOfItems;
    UIView *previous = [carousel itemViewAtIndex:prevIndex];
    AsyncImageView *previousImageView = (AsyncImageView *)[previous viewWithTag:101];
    if (previousImageView.image)
    {
        UIImage *blurImage = [UIImageEffects imageByApplyingLightEffectToImage:previousImageView.image];
        previousImageView.image = blurImage;
    }
}

Now the problem is when it loads at first time, Next and Previous is not getting blurred as it will after scroll.

Need suggestion.

Thanks

**Comment by maulikpat** [comment]
Yes. It worked. Thanks.

I wrote my logic as you suggested in DidScroll: like

`- (void)carouselDidScroll:(iCarousel *)carousel
 {
 NSInteger nextIndex = (carousel.currentItemIndex + 1) %  carousel.numberOfItems;
 UIView *next = [carousel itemViewAtIndex:nextIndex];
 AsyncImageView *nextImageView = (AsyncImageView *)[next  viewWithTag:101];
 if (nextImageView.image)
 {
UIImage *blurImage = [UIImageEffects imageByApplyingLightEffectToImage:nextImageView.image];
nextImageView.image = blurImage;
}

UIView *current = [carousel itemViewAtIndex:carousel.currentItemIndex];
AsyncImageView *currentImageView = (AsyncImageView *)[current viewWithTag:101];
if (currentImageView.image)
{
    HomeThemeData *data = (HomeThemeData *)[self.rotatingImagesArray objectAtIndex:carousel.currentItemIndex];
    currentImageView.imageURL = [NSURL URLWithString:data.ITEM_PATH];
    currentImageView.backgroundColor = [UIColor clearColor];
    current.backgroundColor = [UIColor clearColor];
    current.clipsToBounds = YES;
}

NSInteger prevIndex = (carousel.currentItemIndex + carousel.numberOfItems - 1) % carousel.numberOfItems;
UIView *previous = [carousel itemViewAtIndex:prevIndex];
AsyncImageView *previousImageView = (AsyncImageView *)[previous viewWithTag:101];
if (previousImageView.image)
{
    UIImage *blurImage = [UIImageEffects imageByApplyingLightEffectToImage:previousImageView.image];
    previousImageView.image = blurImage;
}
}`

Now the problem is when it loads at first time, Next and Previous is not getting blurred as it will after scroll.

Need suggestion.

Thanks

**Comment by nicklockwood** [comment]
Don' take this the wrong way, but it seems like you are now asking me to solve trivial programming problems for you, rather than asking for help with iCarousel.

Put your blur logic in a method, and call the method once after you first load the carousel, and again in carouselDidScroll.

**Comment by maulikpat** [comment]
Oops. Anyways thanks for your time and positive replies. I appreciate it.

**Comment by nicklockwood** [comment]
Glad I could help.

**Comment by maulikpat** [comment]
Last one.

Can I assume that after 
self.carousel = [[iCarousel alloc] initWithFrame:CGRectMake(0, 0, ...)]; line, iCarousal is loaded ?

Or any other method ?

**Comment by nicklockwood** [comment]
That's actually a good question.

No, because you haven't set the datasource at that point, so it won't contain any views. You'll need to call it after you've set the datasource/delegate.

It will probably work if you just put it inside viewDidLoad in your carousel view controller. Failing that, if you explicitly call [carousel reloadData] before calling your blur logic for the first time, it should ensure that the carousel views are loaded.

**Comment by maulikpat** [comment]
How about at last line of code ?

self.carousel = [[iCarousel alloc] initWithFrame:CGRectMake(0, 0, viewAnimation.frame.size.width, viewAnimation.frame.size.height)];
self.carousel.dataSource = self;
self.carousel.delegate = self;
self.carousel.type = iCarouselTypeLinear;
[viewAnimation addSubview:self.carousel];

[Here can I assume iCarousal is loaded]

or 
[carousel reloadData];
[Here ?]

**Comment by nicklockwood** [comment]
Why not try it, and see if it works?

**Comment by maulikpat** [comment]
sure..

**Comment by maulikpat** [comment]
after reload, iCarousal has views.

**Comment by tapannathvani** [comment]
Hey Maulik, are you able to blur left & right images.. how can we change the existing images (after blur logic) because when we scroll again the next one should be the original image instead of blur.

**Comment by maulikpat** [comment]
@tapannathvani  Well sorry I don't exactly remember and I don't have code too, but you can manage by Arrays as I guess you can not make original image from Blur. So have separate arrays and manage current index to show original.

**Comment by tapannathvani** [comment]
Okies.. Thanks for the reply. Will check it.
