### ISSUE TITLE
Question: drawing a line between views of the carousel

### ISSUE THREAD

**Issue by tanis2000** [nicklockwood/iCarousel#585]
Hi, I do not know if this is actually doable with iCarousel, but I'm going to ask anyway. 
I'd like to connect the views displayed by iCarousel with a line that toggles between the top, center and bottom of the view pretty much like a linear graph. Would that be doable? And if so, have you got any suggestion as where to start from?

**Comment by Parietal** [comment]
Suggest you go directly to Nick with this one.

**Comment by tanis2000** [comment]
I actually managed to get this working by drawing the lines just like you would if the views were all on the side of each other and you could draw the line from one view to the other. Of course the line gets clipped but that's fine as doing the same from the following view makes it look like they're the same line. Shall anyone need an example of what I did, just shout here :)

**Comment by nico75005** [comment]
Hey Tanis,

Could you please give an example? I've been trying to get one but cannot figure out the exact formula for the line to match my custom shape iCarousel.

**Comment by tanis2000** [comment]
@nico75005 it's been quite some time ago since I wrote the code for that, but basically it was something along these lines:

Header:
```

@interface ALTProfileRankingGraphView : UIView
@property (nonatomic, assign) CGFloat currentY;
@property (nonatomic, assign) CGFloat nextY;
@property (nonatomic, assign) CGFloat prevY;
@end
```

Implementation:
```
@implementation ALTProfileRankingGraphView


// Only override drawRect: if you perform custom drawing.
// An empty implementation adversely affects performance during animation.
- (void)drawRect:(CGRect)rect {
    // Drawing code
    CGContextRef context = UIGraphicsGetCurrentContext();
    
    CGContextSetStrokeColorWithColor(context, [UIColor whiteColor].CGColor);
    
    CGFloat yPos = floorf(self.currentY);
    CGFloat nextYPos = floorf(self.nextY);
    CGFloat prevYPos = floorf(self.prevY);
    
    // Draw them with a 2.0 stroke width so they are a bit more visible.
    CGContextSetLineWidth(context, 2.0f);
    CGContextMoveToPoint(context, self.center.x, yPos); //start at this point
    CGContextAddLineToPoint(context, self.center.x + self.frame.size.width, nextYPos); //draw to this point
    CGContextMoveToPoint(context, self.center.x, yPos); //start at this point
    CGContextAddLineToPoint(context, self.center.x - self.frame.size.width, prevYPos); //draw to this point
    CGContextStrokePath(context);
    
    CGContextMoveToPoint(context, self.center.x, yPos); //start at this point
    CGContextSetLineWidth(context, 2.0f);
    CGContextSetFillColorWithColor(context, [UIColor whiteColor].CGColor);
    CGContextFillEllipseInRect(context, CGRectMake(self.center.x-3, yPos-3, 6, 6));
}


@end
```

And the controller is providing the three Y positions based on the data I'm collecting from a web service. It also does a lot of other stuff as I needed to zoom the central view and make it smaller as I moved it to the sides. If you're still having issues with this I'll try to dig up that controller as well.

**Comment by nico75005** [comment]
All good thanks :)
