### ISSUE TITLE
scrollToItemAtIndex:animated: doesn't work?

### ISSUE THREAD

**Issue by tanb** [nicklockwood/iCarousel#59]
Hi,
I found problem with method "scrollToItemAtIndex:animated: ".

on iOS code, I call this method with an index and animated NO argument.
But it doesn't scroll to the index .

like this:
[carousel scrollToItemAtIndex:4 animated:NO] // not scroll, it'll appear  index 0.

And I tried to replace duration 0 with 0.01 on scrollToItemAtIndex:duration: method.
It seems works well.

Is this bug or not ?

thanks.

**Comment by NandishKesarla** [comment]
Hi nick,

How can I scroll to particular View/Item from swift class ?
I am not able to call scrollToItemAtIndex method

Thanks.
