### ISSUE TITLE
Tapping to stop scrolling accounts as selection

### ISSUE THREAD

**Issue by nickbit** [nicklockwood/iCarousel#602]
Hi Nick,

If the user taps to stop scrolling after swiping, iCarousel sends us the didSelect delegate method.
Tried to block it in the shouldSelect delegate method but the scrolling flag is already set to false.

I also added a LongPress gesture recognizer with a small minimum press duration, but the behavior is not yet acceptable.

Any suggestions?

**Comment by nickbit** [comment]
Finally, I found a solution to this.
```
-(BOOL)carousel:(iCarousel *)carousel shouldSelectItemAtIndex:(NSInteger)index {
    
    if (_blockTapping) {
        _blockTapping = NO;
        return NO;
    }
    ...
}

- (void)carouselDidEndScrollingAnimation:(iCarousel *)carousel {
    _blockTapping = NO;
}

- (void)carouselWillBeginDecelerating:(iCarousel *)carousel {
    _blockTapping = YES;
}
```

**Comment by pankkor** [comment]
This should become a default behaviour

**Comment by slotmaster** [comment]
Agree this should be default.  This is the default behavior for UITableView and UICollectionView.
