### ISSUE TITLE
iCarousel UIView with variable width

### ISSUE THREAD

**Issue by itarataiko** [nicklockwood/iCarousel#62]
Hi Nick,

Can you please help me in my problem?

I have couple of views and width of one of this view smaller than other. How can I set width of this view for linear carousel type?

Thanks

**Comment by briananderson1222** [comment]
It is very unfortunate that this functionality never made it in.. and more so that there were never plans to include it. Is this library still maintained at all?

**Comment by mjesussf** [comment]
I believe it is, but, What do you mean with "UIView with variable width",
the iCarousel width itself or the view width for a caraousel item?

2015-06-24 15:09 GMT-04:30 Brian Anderson <notifications@github.com>:
