### ISSUE TITLE
[autolayout] Linear carousel changes offset of custom views randomly

### ISSUE THREAD

**Issue by dodikk** [nicklockwood/iCarousel#626]
I'm trying to use a view from the storyboard as iCarousel content.
The view has been created in the interface builder entirely (auto layout, no autoresizing masks).

Sometimes the "y" offset of my views becomes incorrect.

![1](https://cloud.githubusercontent.com/assets/396451/8252255/0a90ec66-168d-11e5-9c7b-d5ad0d6c5915.png)
![2](https://cloud.githubusercontent.com/assets/396451/8252240/d9472bde-168c-11e5-9fef-73963186a505.png)

Note : height of the subviews is not correct either (there should be no cyan views visible)

**Comment by dodikk** [comment]
```obj-c
- (UIView *)carousel:(iCarousel *)carousel
  viewForItemAtIndex:(NSInteger)index
         reusingView:(UIView *)view {
    
    UIView* result = view;
    
    if (nil == view)
    {
        UIStoryboard* board = [UIStoryboard storyboardWithName: @"iPhone"
                                                        bundle: nil];
        HLJCommunicationMethodViewOwnerVC* owner = [board instantiateViewControllerWithIdentifier: @"HLJCommunicationMethodViewOwnerVC"];
        
        
        result = owner.view;
    }
    
    result.frame = self->_cellRect; // CGRectMake(0, 0, 240, 327);
    [result layoutIfNeeded];

    // TODO : add data to view
    
    return result;
}


- (CGFloat)carousel:(iCarousel *)carousel
     valueForOption:(iCarouselOption)option
        withDefault:(CGFloat)value {
    
    if (option == iCarouselOptionSpacing)
    {
        return value * self->_carouselSpacingScaleFactor; // 1.08333337
    }
    
    return value;
}
```

**Comment by dodikk** [comment]
![3](https://cloud.githubusercontent.com/assets/396451/8252365/14729c92-168e-11e5-95aa-309058154b0b.png)
![4](https://cloud.githubusercontent.com/assets/396451/8252366/14979736-168e-11e5-8f66-3ddc20b71517.png)

**Comment by dodikk** [comment]
# Solved

The offset has changed since I have not kept the reference to ```HLJCommunicationMethodViewOwnerVC``` instances.

For this reason ```- (void)updateViewConstraints``` has not been called properly.


See the correct loading method below : 

```obj-c
- (UIView *)carousel:(iCarousel *)carousel
  viewForItemAtIndex:(NSInteger)index
         reusingView:(UIView *)view {
    
    UIView* result = view;
    
    if (nil == view)
    {
        UIStoryboard* board = [UIStoryboard storyboardWithName: @"iPhone"
                                                        bundle: nil];
        HLJCommunicationMethodViewOwnerVC* owner = [board instantiateViewControllerWithIdentifier: @"HLJCommunicationMethodViewOwnerVC"];
        

       // This should be done for auto layout views
       [self->_contentViewControllers addObject: owner];
        
        
        result = owner.view;
    }
    
    result.frame = self->_cellRect;
    [result layoutIfNeeded];

    // TODO : add data to view
    
    return result;
}
```

**Comment by vrwim-bazookas** [comment]
@dodikk Could you elaborate on this? What is `_contentViewControllers`?

**Comment by dodikk** [comment]
Some application specific content I wanted to present with iCarousel
