### ISSUE TITLE
How can I use view controllers in iCarousel

### ISSUE THREAD

**Issue by serhatsezer** [nicklockwood/iCarousel#628]
I want to use different type of view controllers like CollectionViewController and UITableViewController as well as I want to use Controller's delegate methods like viewWillAppear: and viewDidLoad: how can I achive this ? 

Simply i'm creating view controllers instance and adding their view to "(CGFloat)carousel:(iCarousel *)carousel valueForOption:(iCarouselOption)option withDefault:(CGFloat)value" delegation method. But their possition are not appropiate.

**Comment by nicklockwood** [comment]
Just create UICollectionViews and UITableViews - you don't need a controller for each view.

**Comment by serhatsezer** [comment]
Hi Nick, Thank you for quick response. But i can't get it. I simply want to create two separate carousel where are placed top and bottom. Top carousel view indicate "which view controller now showed" and bottom carousel show collection view controller. 

Like this framework ; 
https://github.com/uacaps/PageMenu

and here is my gist; 
https://gist.github.com/serhatsezer/0d5200b18d61310d62dc

Thank you so much.

**Comment by serhatsezer** [comment]
@nicklockwood  Do you have an idea?

**Comment by mbcoder17** [comment]
Were you able to get this working as a menu? With one carousel controlling another?

**Comment by serhatsezer** [comment]
@mbcoder17 Yes you can. Let say you have two separate  iCarousel object and their names are "headerCarousel" and "contentCarousel";

- (void)carouselCurrentItemIndexDidChange:(iCarousel *)carousel  {
  
    NSInteger currentItemIndex = carousel.currentItemIndex;

    if(carousel == self.headerCarousel) {
         [self.contentCarousel scrollToItemAtIndex:currentItemIndex animated:YES];
    }
    else if(carousel == self.contentCarousel) {
        [self.headerCarousel scrollToItemAtIndex:currentItemIndex duration:0.8];
    }
}

**Comment by mbcoder17** [comment]
Thanks, but I think Nick's answer from a different issue will work better:

"Yes, you can sync them perfectly. In the carouselDidScroll delegate event of one carousel set the scrollOffset of the other carousel to match the first one (the scrollOffset is now readwrite and public)"
