### ISSUE TITLE
Scroll one by one : Works but not really 

### ISSUE THREAD

**Issue by Aymenworks** [nicklockwood/iCarousel#631]
Hi, sankyu for the carousel open source project :]

I followed some examples to make the carrousel scroll item one by one : 

```swift
  @IBOutlet weak var cardCarousel: iCarousel! {
    didSet {
      self.cardCarousel.type = .Rotary
      self.cardCarousel.scrollEnabled = false
      self.cardCarousel.addGestureRecognizer(UIPanGestureRecognizer(target: self, action: "scrollToNextCardView:"))
    }
  }

func scrollToNextCardView(gesture: UIPanGestureRecognizer) {
    let nextItemIndex = gesture.velocityInView(self.view).x < 0 ? self.cardCarousel.currentItemIndex + 1 : self.cardCarousel.currentItemIndex - 1
    self.cardCarousel.scrollToItemAtIndex(nextItemIndex, duration: CarouselCardView.scrollDuration)
  }
```

It works, but it's not really good. When using default iCarousel behaviour, and when scrolling, the items view follow your gesture. That's a good user experience in my opinion.  With what I did, it doesn't. It just scroll to the next view. There is something like a heavy carousel feeling. You can't see your views moving until you end gesture action, in contrast to the default iCarousel behaviour. It seems it is related to the contentOffset of the carousel and others things like that.

So what can you suggest me for having these two feature in the same time ?

**Comment by nicklockwood** [comment]
That solution is the old way. Now All you have to do is set carousel.pagingEnabled=YES;

**Comment by Aymenworks** [comment]
Thanks you @nicklockwood !
