### ISSUE TITLE
Use two finger scroll showed white line (Vertical Paging)

### ISSUE THREAD

**Issue by jwzhuang** [nicklockwood/iCarousel#634]
My Setting
_carousel.type = iCarouselTypeLinear;
 _carousel.scrollSpeed = 1.0;
 [_carousel setVertical:YES];
 [_carousel setPagingEnabled:YES];
 [_carousel setScrollEnabled:YES];

When I use two finger scroll page , will show a white line between each page 
When one finger scroll first page down,will show white line too.
Any suggest? How to solve it?

one finger
![one finger](https://cloud.githubusercontent.com/assets/8285309/8491945/b2a6d220-2174-11e5-9191-72e38c223129.png) 
two finger
![two finger](https://cloud.githubusercontent.com/assets/8285309/8491947/c9419862-2174-11e5-991a-59c09ba6ee11.png)

**Comment by nicklockwood** [comment]
I think the white line is probably because your image doesn't completely fill the view you are displaying it in. Try using the

    - (CGFloat)carouselItemWidth:(iCarousel *)carousel;

delegate method to return a slightly smaller height for your view (I know the API is called width, but it refers to height in vertical mode).

**Comment by jwzhuang** [comment]
found a way to solve it, use ceil in iCarousel.m
```
case iCarouselTypeLinear:
        {
            CGFloat spacing = [self valueForOption:iCarouselOptionSpacing withDefault:1.0];
            if (_vertical)
            {
                return CATransform3DTranslate(transform, 0.0, ceil(offset * _itemWidth * spacing), 0.0);
            }
            else
            {
                return CATransform3DTranslate(transform, offset * _itemWidth * spacing, 0.0, 0.0);
            }
        }
```
