### ISSUE TITLE
Could not build "Swift Example" project

### ISSUE THREAD

**Issue by maxykato** [nicklockwood/iCarousel#639]
This library looks awesome, and I want to use it in my Swift app project.
I tried building Swift Example project to see how to use the library in Swift but failed to build due to some errors in "ViewController.swift".

I got 4 errors, and 3 of them could be fixed just by following the recommendation by Xcode. 
But there is only one error remaining which is "Method cannot be marked @objc" because the type of the parameter 3 cannot be represented in Objective-C.

How should I fix it?

It would be great if someone can prepare reference manuals for Swift since there will be more and more Swift coders.

**Comment by gopz** [comment]
If you change:

'func carousel(carousel: iCarousel!, viewForItemAtIndex index: Int, var reusingView view: UIView!) -> UIView!'

to 

'func carousel(carousel: iCarousel!, viewForItemAtIndex index: Int, reusingView view: UIView!) -> UIView!'

It should work

**Comment by maxykato** [comment]
Thank you for your help!
Yes, I got another error after I made the fix. 
So should I wait for #640 to be merged and published?

**Comment by youdy3000** [comment]
MaxyKate, did you get it to work?  I am using swift and followed an old answer, similar to gopz's answer.  It works.  I have been using iCarousel for months.

A question I had almost immediately after getting iCarousel to build was solved by the following iCarousel delegate functions:

    // use-case is somebody hitting the value on the carousel
    func carousel(carousel: iCarousel!, didSelectItemAtIndex index: Int) {
        println("the new value should be \(yourArray[index])")
    }
    
    // use-case is somebody selecting the value on the carousel
    func carouselCurrentItemIndexDidChange(carousel: iCarousel!) {
        let index = carousel.currentItemIndex
        println("the new value should be \(yourArray[index])")
    }

**Comment by riyazahemad** [comment]
Hi  @maxykato 

Did you find any fix for the issue with swift example. If yes please share.

**Comment by charlesvinette** [comment]
Same here, numberOfItems is getting called and returns 1 or more, but the viewForItem isn't called at all

**Comment by mlijin9011** [comment]
func carousel(carousel: iCarousel, viewForItemAtIndex index: Int, reusingView view: UIView?) -> UIView 
not call

**Comment by edurd** [comment]
@mlijin9011 Got the same behavior, that function isn't called when run the project, is there any help? Did you manage to get away with this?

**Comment by nicklockwood** [comment]
@edurd you probably just need to use the Swift3 example - the issue you are commenting on is long-since resolved.
