### ISSUE TITLE
iCarousel-Custom Cylinder implementation

### ISSUE THREAD

**Issue by Xcoder89** [nicklockwood/iCarousel#659]
Hey Nick ,
First of all Thanks for this amazing control. Can this be used to create something like in the attached image ?
![preview](https://cloud.githubusercontent.com/assets/10359295/9359555/4fe30784-46af-11e5-82f8-5bc587b31e1c.jpg)

**Comment by nicklockwood** [comment]
Yes, just use the cylinder style and set the contentOffset and viewpointOffset values (you'll want to adjust the y value of both properties to roughly the same value, probably around 200)

**Comment by Xcoder89** [comment]
Thanks for the quick response. This seems to point in the right direction but its kind of Top-Bottom reversed of what I need . Refer the screenshot
i.e  I like to have the front items lower w.r.t the back items.  
Setting the carousel.transform = CGAffineTransformMakeRotation(-M_PI); might be helpful but I'm sure there is a much cleaner way to do this.

![screen shot 2015-08-20 at 1 23 11 am](https://cloud.githubusercontent.com/assets/10359295/9367297/2cd39756-46da-11e5-9597-210c0809ba6d.png)

Thanks again

**Comment by nicklockwood** [comment]
Did you try using -200? ;-)

**Comment by Xcoder89** [comment]
:) Thanks mate
