### ISSUE TITLE
[auto scroll] Is there a implemented method that allows to scroll an item after a time interval?

### ISSUE THREAD

**Issue by nascimentorafael** [nicklockwood/iCarousel#668]
I'm not sure if you got my point so here it is: is there a method that allows the carousel to scroll one item after a time interval?
For example given a carousel with itens from A to Z: Item A is been displayed at first and after x seconds, it scrolls and item B is displayed. And after x seconds it scrolls and item B is displayed, and so on.
I couldn't find any method that does that on the library. If you don't have it I will be glad to implement it.

**Comment by nicklockwood** [comment]
You can do this with an NSTimer that calls scrollByNumberOfItems:1 on the carousel periodically. I don't think there's a huge benefit to building this feature into the library.

**Comment by nascimentorafael** [comment]
Ok!
Thanks a lot Nick!
