### ISSUE TITLE
Does iCarousel work properly with 4.7-inch and 5.5-inch iPhones ?

### ISSUE THREAD

**Issue by LeonardBonfils** [nicklockwood/iCarousel#676]
This library looks great but when I install the "Swift Example" (I only know Swift, I'm not an objective-C guy), the layout is not at all adapted to my iPhone 6S Plus' screen size. Is that because of the Swift Example project configurations or because of the iCarousel library ?

**Comment by jameswalker1995** [comment]
Works fine with auto layout on the objective-C branch. Can't imagine there much difference for auto layout between swift/obj-c? I don't know swift

**Comment by LeonardBonfils** [comment]
Well, I mean... something is clearly wrong, and I haven't changed anything to do with the layout.

http://imgur.com/ZuMEzEN

**Comment by jameswalker1995** [comment]
Can't see anything wrong with the image, which demo are you using?

**Comment by LeonardBonfils** [comment]
Swift Example. The layout is not at all adapted to my iPhone 6S Plus' 5.5" screen. Look at the black areas at the top and bottom of the image.

**Comment by jameswalker1995** [comment]
You probably don't have auto-layout/size classes enabled for the view controller. Try that, and I'll take a look also

**Comment by jameswalker1995** [comment]
Its a problem with the project file. Set Launch Screen File to main.storybord

**Comment by LeonardBonfils** [comment]
Thanks dude, worked flawlessly! Just before I close the issue, why exactly did enabling Main.storyboard as the launch file fix the layout in the rest of the app ?

**Comment by jameswalker1995** [comment]
There was a thing for iPhone 6/6+ and above where to enable 'optimisation' you had to point the apps load screen to something that was optimised and the rest of the app would just follow its lead. Because nothing was set, it defaulted to no, so wasn't optimised. I think thats it anyway, seen that issue on a few projects

**Comment by LeonardBonfils** [comment]
ok cool, thanks for the explanation. Issue closed.
