### ISSUE TITLE
Space between items in iCarousel

### ISSUE THREAD

**Issue by UHemarajU** [nicklockwood/iCarousel#684]
Hi,

I am working with an app that using iCarousel for menu options on top nav. It is working good. For menu items i am using label. Based on the menu text i resized the label width. Here the space between the menu items are not same. I mean for every two menu options the space is not same. Will you please provide me information to solve my problem.

Thanks.

**Comment by UHemarajU** [comment]
Hi,

Here i am attaching image . Please help me.
![Uploading image.png…]()

**Comment by UHemarajU** [comment]
Hi,

Here is image of the carousel. Please help me.
![image](https://cloud.githubusercontent.com/assets/15978550/11337016/b0556c6e-920f-11e5-8e15-dcce02d2068c.png)

**Comment by Shazib** [comment]
Can you check the size of your labels/carousel views? 
Maybe its just white space inside the label thats different

**Comment by nicklockwood** [comment]
It's not possible to have different sizes for each item. iCarousel views must all be the same size, which means that labels of different lengths will not be equally spaced.

You'll probably need to use a UICollectionView for what you want.

**Comment by UHemarajU** [comment]
Hi Shazib,

The size of Label is based on the text length, there is no space inside the Label. The text is fit in the label.
