### ISSUE TITLE
How to add mirror image?

### ISSUE THREAD

**Issue by khuong291** [nicklockwood/iCarousel#692]
I don't know how to implement the mirror image like this? 
May anyone help me with this.

http://i.stack.imgur.com/p6zzu.png

**Comment by nicklockwood** [comment]
Check out the Dynamic Image Effects example included with iCarousel.

**Comment by khuong291** [comment]
Thanks.

**Comment by khuong291** [comment]
I implement these code, but it doesn't work

func carousel(carousel: iCarousel, viewForItemAtIndex index: Int, reusingView view: UIView?) -> UIView {
        
        var itemView: UIImageView
        if (view == nil) {
            itemView = UIImageView(frame:CGRect(x:0, y:0, width:250, height:350))
            itemView.contentMode = .ScaleAspectFit
            viewCarousel.backgroundColor = UIColor(red: 0.0, green: 0.0, blue: 0.0, alpha: 1.0)
        }
        else {
            itemView = view as! UIImageView;
        }

        let imageView = FXImageView(image: images.objectAtIndex(index) as? UIImage)
        imageView.asynchronous = true
        imageView.reflectionScale = 0.5
        imageView.reflectionAlpha = 0.45
        imageView.reflectionGap = 10.0
        imageView.shadowOffset = CGSizeMake(0.0, 2.0)
        imageView.shadowBlur = 5.0
        imageView.cornerRadius = 10.0

        itemView.image = UIImage(named: "\(images.objectAtIndex(index))")
        return itemView
    }

**Comment by nicklockwood** [comment]
You've not added imageView as a  subview of itemView. Also, why are you loading images.objectAtIndex(index) twice?
