### ISSUE TITLE
how to set more than 3 as visible views

### ISSUE THREAD

**Issue by KiranMayeeMaddi** [nicklockwood/iCarousel#710]
Hey, I am a beginner in swift. I have tried Rotary type Carousel effect.I am able to see only 3 views at a time. I need the screen with 3 complete views and 2 views to be placed partially as shown in attachment. 
![carouselrotary](https://cloud.githubusercontent.com/assets/11155409/14048415/148f1ee4-f2d4-11e5-93d6-21a365efcedf.png)
 I have tried changing "**.VisibleItems**" in 
func carousel(carousel: iCarousel, valueForOption option: iCarouselOption, withDefault value: CGFloat) -> CGFloat
but I didnt find any difference. I even tried reducing the view sizes but didnt work out. 

Can anyone help me with all the steps to be performed to get my required result.

**Comment by psy2k** [comment]
There is a `.Spacing` option in carousel options, you can try reducing the spacing between the items using the function you posted and this option.

**Comment by KiranMayeeMaddi** [comment]
Yeah...i have done that..working fine..Thanks a lot for help!!
