### ISSUE TITLE
Xamarin fade?

### ISSUE THREAD

**Issue by shayo** [nicklockwood/iCarousel#742]
How do I enable fade in Xamarin? There isn't a valueForOption in the iCarousel object.

**Comment by nicklockwood** [comment]
I don't maintain the Xamarin project so I'm not sure. valueForOption is a delegate method you implement yourself though, not a property or method you call - perhaps that's the issue?

**Comment by shayo** [comment]
Don't think so. Delegates (events) are visible like other methods and properties

**Comment by jzeferino** [comment]
@shayo I'm the maintainer and creator of the Xamarin binding for ICarousel.
You can check documentation [Xamarin.iOS.iCarousel](https://github.com/jzeferino/Xamarin.iOS.iCarousel)

Regarding your question you must implement the delegate for that:

```
carousel.Delegate = new SimpleDelegate(this);

public class SimpleDelegate : iCarouselDelegate
{    
    public override nfloat ValueForOption(iCarousel carousel, iCarouselOption option, nfloat value)
    {
        switch (option)
        {
           case iCarouselOption.FadeMax:
               return 0.8f;
           case iCarouselOption.FadeMin:
               return 0.8f;
           case iCarouselOption.FadeRange:
               return 0.3f;
           case iCarouselOption.FadeMinAlpha:
               return 0.3f;
        }

        return 1f;
    }
}
```

**Comment by jzeferino** [comment]
@nicklockwood close it please.
