### ISSUE TITLE
iCarousel in tableViewCell

### ISSUE THREAD

**Issue by lubos08** [nicklockwood/iCarousel#746]
Hi, 

I'm using iCarousel in tableViewCell.
In each iCarousel view, I display gif images using https://github.com/Flipboard/FLAnimatedImage
So it requires some loading time for each iCarousel view to load gif images from server and it's blank at the first time before loading gif images.

My problem is when I scroll down to bottom and go back to top tableViewCell again, each iCarousel view is created from scratch, so loading gif images for each cell and the AnimatedImageView is blank again.

Please let me know if there is something like dequeWithReusualCell of tableView.

Thank you.

**Comment by Akariuz** [comment]
Hi, i want to do something similar, did you solve this?

**Comment by lubos08** [comment]
@Akariuz Since I have limited cells on tableView, I have created local array variable [UITableViewCell] and added all of them to the variable.
