### ISSUE TITLE
This is not an issue, but is Query : How to move UIScrollView(in motion) base on iCarousel move, If i am moving Carousel to left the below separate(element) i.e UIScrollview should also move towards the same side.

### ISSUE THREAD

**Issue by tushar666** [nicklockwood/iCarousel#748]

**Comment by nicklockwood** [comment]
In iCarousel's carousel:didScroll delegate event, set the scrollView.contentOffset to match the carousel scrollOffset, and vice-versa.

Note that the units are different, however. ScrollView contentOffset is in pixels, but carousel scrollOffset needs to be multiplied by the itemWidth to get the pixel offset.

**Comment by tushar666** [comment]
Thank you bro!!! Nice trick
