### ISSUE TITLE
How to implement in collectionView cell by Swift?

### ISSUE THREAD

**Issue by kikily** [nicklockwood/iCarousel#759]
I want to add a cell in collectionView by using iCarousel module. I tried to do it but I still got the error message like "Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSObject numberOfItemsInCarousel:]: unrecognized selector sent to instance 0x7fdb66606e20'"

I'm sure I have set the numberOfItemsInCarousel. My code is following.

`class CelebrityDetailHeaderCell: UICollectionViewCell, UITextFieldDelegate, SDCycleScrollViewDelegate, iCarouselDataSource, iCarouselDelegate {

    @IBOutlet weak var backgroudLab: UILabel!
    @IBOutlet weak var name_en: UILabel!
    @IBOutlet weak var name_tw: UILabel!
    @IBOutlet weak var intro: UILabel!
    @IBOutlet weak var DetailImg: UIImageView!
    @IBOutlet weak var iCarouselView: iCarousel!
    
    let screenWidth = UIScreen.mainScreen().bounds.width
    let screenHeight = UIScreen.mainScreen().bounds.height
    
    override func awakeFromNib() {
        super.awakeFromNib()
        
        iCarouselView.delegate = self
        iCarouselView.dataSource = self
        iCarouselView.delegate = self
        iCarouselView.type = .Linear
        
    }
    func numberOfItemsInCarousel(carousel: iCarousel) -> Int {
        return 1
    }
    func carousel(carousel: iCarousel, viewForItemAtIndex index: Int, reusingView view: UIView?) -> UIView {
        let tempView = UIView(frame: CGRect(x: 0, y: screenWidth/2, width: screenWidth, height: screenWidth/2))
        tempView.backgroundColor = UIColor.redColor()
        return tempView
    }
    func carousel(carousel: iCarousel, valueForOption option: iCarouselOption, withDefault value: CGFloat) -> CGFloat {
        if option == iCarouselOption.Spacing {
            return 1.2
        }
        return value
    }

}`
Could anyone give me suggections? Thanks.

**Comment by nicklockwood** [comment]
This was due to dataSource and delegate being bound to the file's owner in the cell's nib file, instead of the cell itself.

**Comment by HrishiPol** [comment]
Hi @nicklockwood  I'm also getting below error. And I'm trying to use it in UIViewController. I don't understand it, where to bound datasource and delegate in it. 
I've tried to bound it with file owner, view...still no luck.
