### ISSUE TITLE
show views of controller from another storyboard correctly using iCarousel

### ISSUE THREAD

**Issue by 6axter82** [nicklockwood/iCarousel#808]
Hi, I am using since couple of days this very nice pod. meanwhile I've got to solve the issue with showing only one card (which is wrong) from storyboard instead of all of them. Maybe you could have a look on it, thanks!

https://stackoverflow.com/questions/44541078/show-views-of-controller-from-another-storyboard-correctly-using-icarousel

**Comment by saito-sv** [comment]
You need to tell icarousel how many items to show. I think my default is only one. So on your options functions switch over it and on .VisableItmes return the amount of times to want to show

**Comment by 6axter82** [comment]
I think it is not the solution, at least it is not the whole one. I still see only one card. Maybe I have to instantiate the VC2 and put them into NSMutableArray in awakeFromNib so many times as many cards I would have.

**Comment by 6axter82** [comment]
I have refactored the code and am using the .xib file from which the view is loaded and reused.
