### ISSUE TITLE
Only the current item can respond to pan gestures.

### ISSUE THREAD

**Issue by CXTretar** [nicklockwood/iCarousel#815]
I add pan gestures to all items, but only the current item can respond to the corresponding gestures.

**Comment by nicklockwood** [comment]
That's by design. Only the currently centered item has userInteractionEnabled.

**Comment by CXTretar** [comment]
Can I change the item's userInteractionEnabled? Does that make a mistake?

**Comment by nicklockwood** [comment]
You'll have to edit the library. There's no option for that.

**Comment by CXTretar** [comment]
I set it like this : 
self.carousel.centerItemWhenSelected = NO; 
and it works.

**Comment by nicklockwood** [comment]
Ah, OK. Yes, that's fine if you don't need that functionality.

**Comment by CXTretar** [comment]
OK, Thanks !!!
