### ISSUE TITLE
How to AutoScroll iCarousel coverflow when view loads

### ISSUE THREAD

**Issue by ghousesgb** [nicklockwood/iCarousel#84]
I mean to scroll the animation, as the view loads, without dragging the images using mouse or fingure.

**Comment by travalarm** [comment]
Hi , i want to scroll iCarousel for infinite time. Is it possible ?

**Comment by nicklockwood** [comment]
You can scroll indefinitely by setting the autoscroll property to a value greater or less than zero.

**Comment by travalarm** [comment]
But it will stop after the time that i given

**Comment by travalarm** [comment]
i set [iCarousel scrollByNumberOfItems:3 duration:INFINITY]; . But its now working

**Comment by BirjuGit** [comment]
I face same issue. I also want to implement autoscroll in iCarousel.Actually my app has requirement like , there are 3 images and i want to autoscroll those images for infinite time until user tap on that images

**Comment by nicklockwood** [comment]
Just set the autoscroll property, then it will scroll at that speed until you set it to zero. No need to call scrollByNumberOfItems:

**Comment by BirjuGit** [comment]
Thanks nicklockwood :) . It's work perfectly. Now , i have only one problem is padding.My image width is 320 (i.e. iPhone screen width) but it leave padding of 10 pixel from left and right. Any properly that set padding 0 ?
