### ISSUE TITLE
I can see the cell on the back in the  gap.

### ISSUE THREAD

**Issue by followSunshine** [nicklockwood/iCarousel#874]
I can see the cell on the back in the gap, and it will appear in mode iCarouselTypeRotary. How to hide the cell on the back without changing the radian and gap width.

**Comment by followSunshine** [comment]
> I can see the cell on the back in the gap, and it will appear in mode iCarouselTypeRotary. How to hide the cell on the back without changing the radian and gap width.

**Comment by pritikumbhar** [comment]
@followSunshine is this issue fixed for you? if yes, can please paste your solution.
