### ISSUE TITLE
How to enable Paging like UIScrollView

### ISSUE THREAD

**Issue by uzman** [nicklockwood/iCarousel#94]
hi.

i use CoverFlow mode. i just want to scroll page by page like UIScrollView (Paging Enabled=TRUE).
is it possible?

**Comment by FreeApple** [comment]
Any possible way too include a "numberOfItemsPerPage" feature? "pagingEnabled" is great but if able too set number of items paging would be fantastic. Thanks

**Comment by nicklockwood** [comment]
Assuming you're using linear mode, try my SwipeView library instead - it has itemsPerPage feature and nearly identical API to iCarousel.

**Comment by FreeApple** [comment]
Yes while in Linear and awesome I will most definitely do so. Thanks for your amazing open source projects!
