### ISSUE TITLE
Rendering outside of UI frame

### ISSUE THREAD

**Issue by josephcc** [nicklockwood/iCarousel#98]
Hi Nick, 

I'm using iCarousel next to other views, and have iCarousel rendering the view items horizontally.
I've notice that iCarousel will render the view items outside of its frame, overlapping to the views adjacent to iCarousel. Is there a way to clip it? Or is there a way I can estimate the actual rendering region?
Thanks!

**Comment by Pranoy1c** [comment]
The `carousel.clipToBounds = YES` simply clips the content instead of fitting it inside the frame of the carousel. Despite setting the ImageView's frame's height equal to the carousel, the imageview goes outside the carousel.

**Comment by nicklockwood** [comment]
@Pranoy1c that's not been my experience. Are you sure that the `carousel` outlet isn't nil, and you're actually setting the property?

**Comment by nicklockwood** [comment]
@Pranoy1c correct. If you want to fit the image inside the carousel you will need to tweak other properties such as the perspective, scale the views, or provide a custom transform.
